export interface Letter {
  kana: string;
  pronunciation: string;
};

export const letters: Record<string, Letter[]> = {
  hiragana: [
    { kana: 'あ', pronunciation: 'a' },
    { kana: 'い', pronunciation: 'i' },
    { kana: 'う', pronunciation: 'u' },
    { kana: 'え', pronunciation: 'e' },
    { kana: 'お', pronunciation: 'o' },
    { kana: 'か', pronunciation: 'ka' },
    { kana: 'き', pronunciation: 'ki' },
    { kana: 'く', pronunciation: 'ku' },
    { kana: 'け', pronunciation: 'ke' },
    { kana: 'こ', pronunciation: 'ko' },
    { kana: 'さ', pronunciation: 'sa' },
    { kana: 'し', pronunciation: 'shi' },
    { kana: 'す', pronunciation: 'su' },
    { kana: 'せ', pronunciation: 'se' },
    { kana: 'そ', pronunciation: 'so' },
    { kana: 'た', pronunciation: 'ta' },
    { kana: 'ち', pronunciation: 'chi' },
    { kana: 'つ', pronunciation: 'tsu' },
    { kana: 'て', pronunciation: 'te' },
    { kana: 'と', pronunciation: 'to' },
    { kana: 'な', pronunciation: 'na' },
    { kana: 'に', pronunciation: 'ni' },
    { kana: 'ぬ', pronunciation: 'nu' },
    { kana: 'ね', pronunciation: 'ne' },
    { kana: 'の', pronunciation: 'no' },
    { kana: 'は', pronunciation: 'ha' },
    { kana: 'ひ', pronunciation: 'hi' },
    { kana: 'ふ', pronunciation: 'fu' },
    { kana: 'へ', pronunciation: 'he' },
    { kana: 'ほ', pronunciation: 'ho' },
    { kana: 'ま', pronunciation: 'ma' },
    { kana: 'み', pronunciation: 'mi' },
    { kana: 'む', pronunciation: 'mu' },
    { kana: 'め', pronunciation: 'me' },
    { kana: 'も', pronunciation: 'mo' },
    { kana: 'や', pronunciation: 'ya' },
    { kana: '', pronunciation: '' },
    { kana: 'ゆ', pronunciation: 'yu' },
    { kana: '', pronunciation: '' },
    { kana: 'よ', pronunciation: 'yo' },
    { kana: 'ら', pronunciation: 'ra' },
    { kana: 'り', pronunciation: 'ri' },
    { kana: 'る', pronunciation: 'ru' },
    { kana: 'れ', pronunciation: 're' },
    { kana: 'ろ', pronunciation: 'ro' },
    { kana: 'わ', pronunciation: 'wa' },
    { kana: '', pronunciation: '' },
    { kana: '', pronunciation: '' },
    { kana: '', pronunciation: '' },
    { kana: 'を', pronunciation: 'wo' },
    { kana: 'ん', pronunciation: 'n' },
  ],
  katakana: [
    { kana: 'ア', pronunciation: 'a' },
    { kana: 'イ', pronunciation: 'i' },
    { kana: 'ウ', pronunciation: 'u' },
    { kana: 'エ', pronunciation: 'e' },
    { kana: 'オ', pronunciation: 'o' },
    { kana: 'カ', pronunciation: 'ka' },
    { kana: 'キ', pronunciation: 'ki' },
    { kana: 'ク', pronunciation: 'ku' },
    { kana: 'ケ', pronunciation: 'ke' },
    { kana: 'コ', pronunciation: 'ko' },
    { kana: 'サ', pronunciation: 'sa' },
    { kana: 'シ', pronunciation: 'shi' },
    { kana: 'ス', pronunciation: 'su' },
    { kana: 'セ', pronunciation: 'se' },
    { kana: 'ソ', pronunciation: 'so' },
    { kana: 'タ', pronunciation: 'ta' },
    { kana: 'チ', pronunciation: 'chi' },
    { kana: 'ツ', pronunciation: 'tsu' },
    { kana: 'テ', pronunciation: 'te' },
    { kana: 'ト', pronunciation: 'to' },
    { kana: 'ナ', pronunciation: 'na' },
    { kana: 'ニ', pronunciation: 'ni' },
    { kana: 'ヌ', pronunciation: 'nu' },
    { kana: 'ネ', pronunciation: 'ne' },
    { kana: 'ノ', pronunciation: 'no' },
    { kana: 'ハ', pronunciation: 'ha' },
    { kana: 'ヒ', pronunciation: 'hi' },
    { kana: 'フ', pronunciation: 'fu' },
    { kana: 'ヘ', pronunciation: 'he' },
    { kana: 'ホ', pronunciation: 'ho' },
    { kana: 'マ', pronunciation: 'ma' },
    { kana: 'ミ', pronunciation: 'mi' },
    { kana: 'ム', pronunciation: 'mu' },
    { kana: 'メ', pronunciation: 'me' },
    { kana: 'モ', pronunciation: 'mo' },
    { kana: 'ヤ', pronunciation: 'ya' },
    { kana: '', pronunciation: '' },
    { kana: 'ユ', pronunciation: 'yu' },
    { kana: '', pronunciation: '' },
    { kana: 'ヨ', pronunciation: 'yo' },
    { kana: 'ラ', pronunciation: 'ra' },
    { kana: 'リ', pronunciation: 'ri' },
    { kana: 'ル', pronunciation: 'ru' },
    { kana: 'レ', pronunciation: 're' },
    { kana: 'ロ', pronunciation: 'ro' },
    { kana: 'ワ', pronunciation: 'wa' },
    { kana: '', pronunciation: '' },
    { kana: '', pronunciation: '' },
    { kana: '', pronunciation: '' },
    { kana: 'ヲ', pronunciation: 'wo' },
    { kana: 'ン', pronunciation: 'n' },
  ],
}